language: c

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install build-essential make libpurple-dev libmrss0-dev pidgin
  - sudo apt-get build-dep libpurple0

script:
  - make
  - sudo make install

notifications:
  email:
    recipients:
      - moraxy@users.noreply.github.com
    on_success: always
